//package com.rules.trojan

import com.model.problem.Trojan
import com.model.other.Time
import com.model.other.Type
import com.model.other.Item

// This rule is a naive simple to detect Trojan in KMeans
// Key Logic:
1. 进行数据筛选，将只有upload/download的数据筛选出来
2. 从基础数据中获取八个维度的数据,组成一个向量
3. 这个向量，通过已经学习好的KMEANS模型进行判定
4. 判定出的结果输出到数据库

//=========================================================================
// Set the runtime environment
//=========================================================================
rule "SET: begin detection time"
   salience 100
   lock-on-active true
   dialect "mvel"
   when
     $time : Time()
   then
     $time.setbeginTime(1480867200)
     System.out.println("  [Rule]  SET: begin detection time 1490630400")
     update($time)
end

rule "SET: end detection time"
   salience 100
   lock-on-active true
   dialect "mvel"
   when
     $time : Time()
   then
     $time.setendTime(1480870000)
     System.out.println("  [Rule]  SET: end detection time 1490634000") 
     update($time)
end

rule "VERIFY: verify the time operation"
   //lock-on-active true
   dialect "mvel"
   when
     $time : Time(beginTime == 1490630400 && endTime == 1490634000)
   then
     System.out.println("  [Rule]  VERIFY: verify the time operation :Correct")
end

rule "SET: detection type"
   lock-on-active true
   dialect "mvel"
   when
     $type : Type()
   then
     $type.setType("Trojan in KMeans")
     System.out.println("  [Rule]  SET: end detection type Trojan")
     update($type)
end


//==========================================================================
// Set the statistical data required for judgement
//=========================================================================

rule "Filter : Filter the item with both upload&download"
   lock-on-active true
   salience 20
   dialect "mvel"
   when
     $item : Item( up_count>0 && down_count>0)
   then
     $item.setValid()
     System.out.println("  [Rule]  Filter : Filter the item with both upload&download "+$item.obj)
     //update($item)
end


rule "Add Dimesion: Upload-Download-Count-Ratio "
   lock-on-active true
   salience 10
   dialect "mvel"
   when
     $item : Item(isValid==True)
   then
     $item.addDimension("Upload-Download-Count-Ratio",$item.up_count/$item.down_count)
     System.out.println("  [Rule]  Add Dimesion: Upload-Download-Count-Ratio "+$item.obj)
     //update($item)
end


rule "Add Dimesion: Upload-Download-Size-Ratio "
   lock-on-active true
   salience 10
   dialect "mvel"
   when
     $item : Item(isValid==True)
   then
     $item.addDimension("Upload-Download-Size-Ratio",$item.up_size/$item.down_size)
     System.out.println("  [Rule]  Add Dimesion: Upload-Download-Size-Ratio "+$item.obj)
     //update($item)
end

rule "Add Dimesion: SYN-Ratio "
   lock-on-active true
   salience 10
   dialect "mvel"
   when
     $item : Item(isValid==True)
   then
     $item.addDimension("SYN-Ratio",$item.syn/$item.up_count)
     System.out.println("  [Rule]  Add Dimesion: SYN-Ratio "+$item.obj)
     //update($item)
end

rule "Add Dimesion: PSH-Ratio "
   lock-on-active true
   salience 10
   dialect "mvel"
   when
     $item : Item(isValid==True)
   then
     $item.addDimension("PSH-Ratio",$item.psh/$item.down_count)
     System.out.println("  [Rule]  Add Dimesion: PSH-Ratio "+$item.obj)
     //update($item)
end

rule "Add Dimension: DNS Count"
   lock-on-active true
   salience 10
   dialect "mvel"
   when
     $item : Item(isValid==True)
   then
     $item.addDimension("DNS",$item.dns)
     System.out.println("  [Rule]  Add Dimesion: DNS "+$item.obj)
     //update($item)
end

rule "Add Dimension: Upload Small Ration"
   lock-on-active true
   salience 10
   dialect "mvel"
   when
     $item : Item(isValid==True)
   then
     $item.addDimension("Upload-Small-Ratio",$item.up_small/$item.up_count)
     System.out.println("  [Rule]  Add Dimension: Upload Small Ration "+$item.obj)
     //update($item)
end

rule "Add Dimension: Session Time"
   lock-on-active true
   salience 10
   dialect "mvel"
   when
     $item : Item(isValid==True)
   then
     $item.addDimension("Session Time",$item.sessionTime)
     System.out.println("  [Rule]  Add Dimension: Upload Small Ration "+$item.obj)
     //update($item)
end

rule "KMeans Judgement"
   lock-on-active true
   salience 5
   dialect "mvel"
   when
     $item : Item(dimensionNum==7)
   then
     $item.SA_KMEANS_JUDGEMENT($time,"Upload-Download-Count-Ratio","Upload-Download-Size-Ratio","SYN-Ratio","PSH-Ratio","DNS","Upload-Small-Ratio","Session Time")
     System.out.println("  [Rule]  KMeans Judgement: "+$item.obj)
end

rule "Save to Data Base"
   lock-on-active true
   salience 1
   dialect "mvel"
   when
     $item : Item(problems contains "Trojan KMeans Detection Target")
   then
     $item.save_to_database()
     System.out.println("  [Rule]  Save to Data Base: "+$item.obj)
end
