// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interface.proto

package com.rpc;

public final class Interface {
  private Interface() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code rpc.RequestMode}
   */
  public enum RequestMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT = 0;</code>
     */
    DEFAULT(0, 0),
    /**
     * <code>OPTIMIZED = 1;</code>
     */
    OPTIMIZED(1, 1),
    /**
     * <code>SIMPLE = 2;</code>
     */
    SIMPLE(2, 2),
    ;

    /**
     * <code>DEFAULT = 0;</code>
     */
    public static final int DEFAULT_VALUE = 0;
    /**
     * <code>OPTIMIZED = 1;</code>
     */
    public static final int OPTIMIZED_VALUE = 1;
    /**
     * <code>SIMPLE = 2;</code>
     */
    public static final int SIMPLE_VALUE = 2;


    public final int getNumber() { return value; }

    public static RequestMode valueOf(int value) {
      switch (value) {
        case 0: return DEFAULT;
        case 1: return OPTIMIZED;
        case 2: return SIMPLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestMode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestMode>() {
            public RequestMode findValueByNumber(int number) {
              return RequestMode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rpc.Interface.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestMode[] VALUES = values();

    public static RequestMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RequestMode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rpc.RequestMode)
  }

  public interface VectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.Vector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float value = 1;</code>
     */
    java.util.List<java.lang.Float> getValueList();
    /**
     * <code>repeated float value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>repeated float value = 1;</code>
     */
    float getValue(int index);
  }
  /**
   * Protobuf type {@code rpc.Vector}
   */
  public static final class Vector extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.Vector)
      VectorOrBuilder {
    // Use Vector.newBuilder() to construct.
    private Vector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Vector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Vector defaultInstance;
    public static Vector getDefaultInstance() {
      return defaultInstance;
    }

    public Vector getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Vector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                value_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              value_.add(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                value_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                value_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = java.util.Collections.unmodifiableList(value_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpc.Interface.internal_static_rpc_Vector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpc.Interface.internal_static_rpc_Vector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpc.Interface.Vector.class, com.rpc.Interface.Vector.Builder.class);
    }

    public static com.google.protobuf.Parser<Vector> PARSER =
        new com.google.protobuf.AbstractParser<Vector>() {
      public Vector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vector(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Vector> getParserForType() {
      return PARSER;
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> value_;
    /**
     * <code>repeated float value = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated float value = 1;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated float value = 1;</code>
     */
    public float getValue(int index) {
      return value_.get(index);
    }

    private void initFields() {
      value_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < value_.size(); i++) {
        output.writeFloat(1, value_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getValueList().size();
        size += dataSize;
        size += 1 * getValueList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rpc.Interface.Vector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rpc.Interface.Vector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rpc.Interface.Vector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rpc.Interface.Vector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rpc.Interface.Vector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rpc.Interface.Vector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rpc.Interface.Vector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rpc.Interface.Vector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rpc.Interface.Vector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rpc.Interface.Vector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rpc.Interface.Vector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.Vector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.Vector)
        com.rpc.Interface.VectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rpc.Interface.internal_static_rpc_Vector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rpc.Interface.internal_static_rpc_Vector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rpc.Interface.Vector.class, com.rpc.Interface.Vector.Builder.class);
      }

      // Construct using com.rpc.Interface.Vector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rpc.Interface.internal_static_rpc_Vector_descriptor;
      }

      public com.rpc.Interface.Vector getDefaultInstanceForType() {
        return com.rpc.Interface.Vector.getDefaultInstance();
      }

      public com.rpc.Interface.Vector build() {
        com.rpc.Interface.Vector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rpc.Interface.Vector buildPartial() {
        com.rpc.Interface.Vector result = new com.rpc.Interface.Vector(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rpc.Interface.Vector) {
          return mergeFrom((com.rpc.Interface.Vector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rpc.Interface.Vector other) {
        if (other == com.rpc.Interface.Vector.getDefaultInstance()) return this;
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rpc.Interface.Vector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rpc.Interface.Vector) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Float> value_ = java.util.Collections.emptyList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = new java.util.ArrayList<java.lang.Float>(value_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float value = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getValueList() {
        return java.util.Collections.unmodifiableList(value_);
      }
      /**
       * <code>repeated float value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated float value = 1;</code>
       */
      public float getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated float value = 1;</code>
       */
      public Builder setValue(
          int index, float value) {
        ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float value = 1;</code>
       */
      public Builder addValue(float value) {
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float value = 1;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float value = 1;</code>
       */
      public Builder clearValue() {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rpc.Vector)
    }

    static {
      defaultInstance = new Vector(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rpc.Vector)
  }

  public interface IRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.IRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 num = 2;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 num = 2;</code>
     */
    int getNum();

    /**
     * <code>required int32 parent = 3;</code>
     */
    boolean hasParent();
    /**
     * <code>required int32 parent = 3;</code>
     */
    int getParent();

    /**
     * <code>required int32 beginTime = 4;</code>
     */
    boolean hasBeginTime();
    /**
     * <code>required int32 beginTime = 4;</code>
     */
    int getBeginTime();

    /**
     * <code>required int32 endTime = 5;</code>
     */
    boolean hasEndTime();
    /**
     * <code>required int32 endTime = 5;</code>
     */
    int getEndTime();

    /**
     * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
     */
    boolean hasMode();
    /**
     * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
     */
    com.rpc.Interface.RequestMode getMode();

    /**
     * <code>optional .rpc.Vector vector = 7;</code>
     */
    boolean hasVector();
    /**
     * <code>optional .rpc.Vector vector = 7;</code>
     */
    com.rpc.Interface.Vector getVector();
    /**
     * <code>optional .rpc.Vector vector = 7;</code>
     */
    com.rpc.Interface.VectorOrBuilder getVectorOrBuilder();
  }
  /**
   * Protobuf type {@code rpc.IRequest}
   */
  public static final class IRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.IRequest)
      IRequestOrBuilder {
    // Use IRequest.newBuilder() to construct.
    private IRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IRequest defaultInstance;
    public static IRequest getDefaultInstance() {
      return defaultInstance;
    }

    public IRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              num_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              parent_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              beginTime_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              endTime_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.rpc.Interface.RequestMode value = com.rpc.Interface.RequestMode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                mode_ = value;
              }
              break;
            }
            case 58: {
              com.rpc.Interface.Vector.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = vector_.toBuilder();
              }
              vector_ = input.readMessage(com.rpc.Interface.Vector.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vector_);
                vector_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpc.Interface.internal_static_rpc_IRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpc.Interface.internal_static_rpc_IRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpc.Interface.IRequest.class, com.rpc.Interface.IRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<IRequest> PARSER =
        new com.google.protobuf.AbstractParser<IRequest>() {
      public IRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <code>required int32 num = 2;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 num = 2;</code>
     */
    public int getNum() {
      return num_;
    }

    public static final int PARENT_FIELD_NUMBER = 3;
    private int parent_;
    /**
     * <code>required int32 parent = 3;</code>
     */
    public boolean hasParent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 parent = 3;</code>
     */
    public int getParent() {
      return parent_;
    }

    public static final int BEGINTIME_FIELD_NUMBER = 4;
    private int beginTime_;
    /**
     * <code>required int32 beginTime = 4;</code>
     */
    public boolean hasBeginTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 beginTime = 4;</code>
     */
    public int getBeginTime() {
      return beginTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 5;
    private int endTime_;
    /**
     * <code>required int32 endTime = 5;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 endTime = 5;</code>
     */
    public int getEndTime() {
      return endTime_;
    }

    public static final int MODE_FIELD_NUMBER = 6;
    private com.rpc.Interface.RequestMode mode_;
    /**
     * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
     */
    public boolean hasMode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
     */
    public com.rpc.Interface.RequestMode getMode() {
      return mode_;
    }

    public static final int VECTOR_FIELD_NUMBER = 7;
    private com.rpc.Interface.Vector vector_;
    /**
     * <code>optional .rpc.Vector vector = 7;</code>
     */
    public boolean hasVector() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .rpc.Vector vector = 7;</code>
     */
    public com.rpc.Interface.Vector getVector() {
      return vector_;
    }
    /**
     * <code>optional .rpc.Vector vector = 7;</code>
     */
    public com.rpc.Interface.VectorOrBuilder getVectorOrBuilder() {
      return vector_;
    }

    private void initFields() {
      name_ = "";
      num_ = 0;
      parent_ = 0;
      beginTime_ = 0;
      endTime_ = 0;
      mode_ = com.rpc.Interface.RequestMode.DEFAULT;
      vector_ = com.rpc.Interface.Vector.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBeginTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, parent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, beginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, endTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, vector_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, parent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, beginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, endTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, vector_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rpc.Interface.IRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rpc.Interface.IRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rpc.Interface.IRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rpc.Interface.IRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rpc.Interface.IRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rpc.Interface.IRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rpc.Interface.IRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rpc.Interface.IRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rpc.Interface.IRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rpc.Interface.IRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rpc.Interface.IRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.IRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.IRequest)
        com.rpc.Interface.IRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rpc.Interface.internal_static_rpc_IRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rpc.Interface.internal_static_rpc_IRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rpc.Interface.IRequest.class, com.rpc.Interface.IRequest.Builder.class);
      }

      // Construct using com.rpc.Interface.IRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVectorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        parent_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        beginTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        mode_ = com.rpc.Interface.RequestMode.DEFAULT;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (vectorBuilder_ == null) {
          vector_ = com.rpc.Interface.Vector.getDefaultInstance();
        } else {
          vectorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rpc.Interface.internal_static_rpc_IRequest_descriptor;
      }

      public com.rpc.Interface.IRequest getDefaultInstanceForType() {
        return com.rpc.Interface.IRequest.getDefaultInstance();
      }

      public com.rpc.Interface.IRequest build() {
        com.rpc.Interface.IRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rpc.Interface.IRequest buildPartial() {
        com.rpc.Interface.IRequest result = new com.rpc.Interface.IRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.parent_ = parent_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.beginTime_ = beginTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.mode_ = mode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (vectorBuilder_ == null) {
          result.vector_ = vector_;
        } else {
          result.vector_ = vectorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rpc.Interface.IRequest) {
          return mergeFrom((com.rpc.Interface.IRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rpc.Interface.IRequest other) {
        if (other == com.rpc.Interface.IRequest.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasParent()) {
          setParent(other.getParent());
        }
        if (other.hasBeginTime()) {
          setBeginTime(other.getBeginTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasVector()) {
          mergeVector(other.getVector());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        if (!hasParent()) {
          
          return false;
        }
        if (!hasBeginTime()) {
          
          return false;
        }
        if (!hasEndTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rpc.Interface.IRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rpc.Interface.IRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <code>required int32 num = 2;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 num = 2;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 num = 2;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000002;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num = 2;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        onChanged();
        return this;
      }

      private int parent_ ;
      /**
       * <code>required int32 parent = 3;</code>
       */
      public boolean hasParent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 parent = 3;</code>
       */
      public int getParent() {
        return parent_;
      }
      /**
       * <code>required int32 parent = 3;</code>
       */
      public Builder setParent(int value) {
        bitField0_ |= 0x00000004;
        parent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 parent = 3;</code>
       */
      public Builder clearParent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        parent_ = 0;
        onChanged();
        return this;
      }

      private int beginTime_ ;
      /**
       * <code>required int32 beginTime = 4;</code>
       */
      public boolean hasBeginTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 beginTime = 4;</code>
       */
      public int getBeginTime() {
        return beginTime_;
      }
      /**
       * <code>required int32 beginTime = 4;</code>
       */
      public Builder setBeginTime(int value) {
        bitField0_ |= 0x00000008;
        beginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 beginTime = 4;</code>
       */
      public Builder clearBeginTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        beginTime_ = 0;
        onChanged();
        return this;
      }

      private int endTime_ ;
      /**
       * <code>required int32 endTime = 5;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 endTime = 5;</code>
       */
      public int getEndTime() {
        return endTime_;
      }
      /**
       * <code>required int32 endTime = 5;</code>
       */
      public Builder setEndTime(int value) {
        bitField0_ |= 0x00000010;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 endTime = 5;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        endTime_ = 0;
        onChanged();
        return this;
      }

      private com.rpc.Interface.RequestMode mode_ = com.rpc.Interface.RequestMode.DEFAULT;
      /**
       * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
       */
      public boolean hasMode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
       */
      public com.rpc.Interface.RequestMode getMode() {
        return mode_;
      }
      /**
       * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
       */
      public Builder setMode(com.rpc.Interface.RequestMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .rpc.RequestMode mode = 6 [default = DEFAULT];</code>
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mode_ = com.rpc.Interface.RequestMode.DEFAULT;
        onChanged();
        return this;
      }

      private com.rpc.Interface.Vector vector_ = com.rpc.Interface.Vector.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.rpc.Interface.Vector, com.rpc.Interface.Vector.Builder, com.rpc.Interface.VectorOrBuilder> vectorBuilder_;
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public boolean hasVector() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public com.rpc.Interface.Vector getVector() {
        if (vectorBuilder_ == null) {
          return vector_;
        } else {
          return vectorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public Builder setVector(com.rpc.Interface.Vector value) {
        if (vectorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vector_ = value;
          onChanged();
        } else {
          vectorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public Builder setVector(
          com.rpc.Interface.Vector.Builder builderForValue) {
        if (vectorBuilder_ == null) {
          vector_ = builderForValue.build();
          onChanged();
        } else {
          vectorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public Builder mergeVector(com.rpc.Interface.Vector value) {
        if (vectorBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              vector_ != com.rpc.Interface.Vector.getDefaultInstance()) {
            vector_ =
              com.rpc.Interface.Vector.newBuilder(vector_).mergeFrom(value).buildPartial();
          } else {
            vector_ = value;
          }
          onChanged();
        } else {
          vectorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public Builder clearVector() {
        if (vectorBuilder_ == null) {
          vector_ = com.rpc.Interface.Vector.getDefaultInstance();
          onChanged();
        } else {
          vectorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public com.rpc.Interface.Vector.Builder getVectorBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getVectorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      public com.rpc.Interface.VectorOrBuilder getVectorOrBuilder() {
        if (vectorBuilder_ != null) {
          return vectorBuilder_.getMessageOrBuilder();
        } else {
          return vector_;
        }
      }
      /**
       * <code>optional .rpc.Vector vector = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.rpc.Interface.Vector, com.rpc.Interface.Vector.Builder, com.rpc.Interface.VectorOrBuilder> 
          getVectorFieldBuilder() {
        if (vectorBuilder_ == null) {
          vectorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.rpc.Interface.Vector, com.rpc.Interface.Vector.Builder, com.rpc.Interface.VectorOrBuilder>(
                  getVector(),
                  getParentForChildren(),
                  isClean());
          vector_ = null;
        }
        return vectorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:rpc.IRequest)
    }

    static {
      defaultInstance = new IRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rpc.IRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Vector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_Vector_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_IRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_IRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017interface.proto\022\003rpc\"\027\n\006Vector\022\r\n\005valu" +
      "e\030\001 \003(\002\"\237\001\n\010IRequest\022\014\n\004name\030\001 \002(\t\022\013\n\003nu" +
      "m\030\002 \002(\005\022\016\n\006parent\030\003 \002(\005\022\021\n\tbeginTime\030\004 \002" +
      "(\005\022\017\n\007endTime\030\005 \002(\005\022\'\n\004mode\030\006 \001(\0162\020.rpc." +
      "RequestMode:\007DEFAULT\022\033\n\006vector\030\007 \001(\0132\013.r" +
      "pc.Vector*5\n\013RequestMode\022\013\n\007DEFAULT\020\000\022\r\n" +
      "\tOPTIMIZED\020\001\022\n\n\006SIMPLE\020\002B\024\n\007com.rpcB\tInt" +
      "erface"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rpc_Vector_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_Vector_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_rpc_IRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_IRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_IRequest_descriptor,
        new java.lang.String[] { "Name", "Num", "Parent", "BeginTime", "EndTime", "Mode", "Vector", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
