//package com.rules.trojan

import com.model.problem.Trojan
import com.model.other.Time
import com.model.other.Type
import com.model.Item
import com.service.TroDItem

// This rule is a naive simple to detect Trojan in KMeans
// Key Logic:
//1. 进行数据筛选，将只有upload/download的数据筛选出来
//2. 从基础数据中获取八个维度的数据,组成一个向量
//3. 这个向量，通过已经学习好的KMEANS模型进行判定
//4. 判定出的结果输出到数据库



//=========================================================================
// Set the runtime environment
//=========================================================================

global java.util.List kvector

rule "SET: begin detection time"
   salience 100
   lock-on-active true
   dialect "mvel"
   when
     $time : Time()
   then
     $time.setbeginTime(1480867200)
     System.out.println("  [Rule]  SET: begin detection time 1490630400")
     update($time)
end

rule "SET: end detection time"
   salience 100
   lock-on-active true
   dialect "mvel"
   when
     $time : Time()
   then
     $time.setendTime(1480870000)
     System.out.println("  [Rule]  SET: end detection time 1490634000") 
     update($time)
end

rule "VERIFY: verify the time operation"
   //lock-on-active true
   dialect "mvel"
   when
     $time : Time(beginTime == 1490630400 && endTime == 1490634000)
   then
     System.out.println("  [Rule]  VERIFY: verify the time operation :Correct")
end

rule "SET: detection type"
   lock-on-active true
   dialect "mvel"
   when
     $type : Type()
   then
     $type.setType("Trojan in KMeans")
     System.out.println("  [Rule]  SET: end detection type Trojan")
     update($type)
     drools.setFocus("Filter")
end


//==========================================================================
// Set the statistical data required for judgement
//=========================================================================

rule "Filter : Filter the item with both upload&download"
   no-loop true
   //lock-on-active true
   agenda-group "Filter"
   salience 25
   dialect "mvel"
   when
     $item : Item( up_count>0 && down_count>0 && status == 0)
   then
     $item.setValid()
     System.out.println("  [Rule]  Filter : Filter the item with both upload&download "+$item.obj)
     update($item)
end

rule "Filter : Conclusion"
   no-loop true
   //lock-on-active true
   agenda-group "Filter"
   salience 20
   dialect "mvel"
   when
     $item : Item( valid == true && status == 0)
   then
     $item.setStatus(1)
     update($item)
     System.out.println("  [Rule]  Filter : Filter conclusion "+$item.obj)
     drools.setFocus("Dimension Addition")
end

//==========================================================================
// Insert Dimension
//=========================================================================

rule "Add Dimesion: Upload-Download-Count-Ratio "
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 10
   dialect "mvel"
   when
     $item : Item( valid == true)
   then
     Double newD = $item.up_count/$item.down_count
     $item.addDimension("Upload-Download-Count-Ratio",newD)
     System.out.println("  [Rule]  Add Dimesion: Upload-Download-Count-Ratio " + $item.obj + " "+ newD)
     update($item)
end


rule "Add Dimesion: Upload-Download-Size-Ratio "
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 10
   dialect "mvel"
   when
     $item : Item( valid == true)
   then
     Double newD = $item.up_size/$item.down_size
     $item.addDimension("Upload-Download-Size-Ratio",newD)
     System.out.println("  [Rule]  Add Dimesion: Upload-Download-Size-Ratio "+$item.obj + " "+ newD)
     update($item)
end

rule "Add Dimesion: SYN-Ratio "
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 10
   dialect "mvel"
   when
     $item : Item( valid == true)
   then
     Double newD = $item.syn/$item.up_count
     $item.addDimension("SYN-Ratio",  newD)
     System.out.println("  [Rule]  Add Dimesion: SYN-Ratio "+$item.obj+ " "+ newD)
     update($item)
end

rule "Add Dimesion: PSH-Ratio "
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 10
   dialect "mvel"
   when
     $item : Item( valid == true)
   then
     Double newD = $item.psh/$item.down_count
     $item.addDimension("PSH-Ratio",newD)
     System.out.println("  [Rule]  Add Dimesion: PSH-Ratio "+$item.obj + " "+ newD)
     update($item)
end

rule "Add Dimension: DNS Count"
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 10
   dialect "mvel"
   when
     $item : Item( valid == true)
   then
     $item.addDimension("DNS",$item.dns)
     System.out.println("  [Rule]  Add Dimesion: DNS "+$item.obj+ " "+$item.dns)
     update($item)
end

rule "Add Dimension: Upload Small Ration"
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 10
   dialect "mvel"
   when
     $item : Item( valid == true)
   then
     Double newD = $item.up_small/$item.up_count
     $item.addDimension("Upload-Small-Ratio", newD)
     System.out.println("  [Rule]  Add Dimension: Upload Small Ration "+$item.obj + " "+ newD)
     update($item)
end

rule "Add Dimension: Session Time"
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 10
   dialect "mvel"
   when
     $item : Item( valid == true)
   then
     Double newD = $item.session_total / $item.session_count
     $item.addDimension("Session Time",newD)
     System.out.println("  [Rule]  Add Dimension: Average Session Time "+$item.obj+ " "+ newD)
     update($item)
end

rule "Add Dimension: Conclusion"
   no-loop true
   lock-on-active true
   agenda-group "Dimension Addition"
   salience 9
   dialect "mvel"
   when
     $item : Item( valid == true && status == 1)
   then
     $item.setStatus(2)
     update($item)
     System.out.println("  [Rule]  Add Dimension: Conclusion "+$item.obj)
     drools.setFocus("Judgement")
end

//==========================================================================
// Insert Dimension
//=========================================================================
rule "KMeans Judgement"
   lock-on-active true
   agenda-group "Judgement" 
   salience 5
   dialect "mvel"
   when
     $item :TroDItem( valid == true)
     $time :Time()
   then
     $item.SA_KMEANS_JUDGEMENT($time,["Session Time","DNS","Upload-Download-Count-Ratio","Upload-Download-Size-Ratio","SYN_RATIO","PSH_RATIO","Upload-Small-Ratio"])
     System.out.println("  [Rule]  KMeans Judgement: "+$item.obj)
end


/*
rule "Save to Data Base"
   salience 1
   dialect "mvel"
   when
     $item : Item(problems contains "Trojan KMeans Detection Target")
   then
     $item.save_to_database()
     System.out.println("  [Rule]  Save to Data Base: "+$item.obj)
end
*/
